[repository]
enable_commit = true

[[transforms]]
path = 'Cargo.toml'
replace = 'version = "{version}"'

[[transforms]]
path = 'Cargo.lock'
replace = """\
[[package]]
name = "git-squish"
version = "{version}"
"""